INSERT INTO patients(first_name, last_name) VALUES('John', 'Smith');

INSERT INTO patients(first_name, last_name) VALUES('Jane', 'Bingham');

INSERT INTO records(patient_id, title, description, date) VALUES(1, 'Chronic Issues', 'Mr. Smith is a 63-year-old gentleman with coronary artery disease, hypertension, hypercholesterolemia, COPD and tobacco abuse. He reports doing well. He did have some more knee pain for a few weeks, but this has resolved. He is having more trouble with his sinuses. I had started him on Flonase back in December. He says this has not really helped. Over the past couple weeks he has had significant congestion and thick discharge. No fevers or headaches but does have diffuse upper right-sided teeth pain. He denies any chest pains, palpitations, PND, orthopnea, edema or syncope. His breathing is doing fine. No cough. He continues to smoke about half-a-pack per day. He plans on trying the patches again.', '2000-10-12');

INSERT INTO records(patient_id, title, description) VALUES(1, 'More Chronic Issues', 'Mr. Smith is a 66-year-old gentleman with hypertension and hypercholesterolemia. He reports he is overall doing well. He is not having any trouble with his medications. His blood pressures generally have been running around 140/90 at home. He has been having low back pain for the past 6 months. It is more on the right side and occurs intermittently throughout the day. No known initial precipitating event. He denies any radiation down his legs, any fevers, night sweats, weight loss, or bowel or bladder problems. Of note, he did have significant radiation in this area many years ago for treatment for skin cancer. He is not getting much exercise.');

INSERT INTO records(patient_id, title, description, date) VALUES(2, 'Sore Throat', 'Ms. Bingham is a 24 yo woman who complains of worsening sore throat since yesterday morning. She has never had a similar problem in the past. She has no difficulty swallowing, but notes that swallowing makes the pain worse. Nothing makes it better. There is no SOB or sensation of choking or dysphagia. She has fatigue and has had some anorexia since the symptoms began. She has had some subjective fevers at home but has not taken her temperature. She has had no cough or rhinorrhea. There are no sick contacts at home or at work. She denies seasonal allergies and post-nasal drip. ROS: No chest pain, cough, wheezing, abdominal pain, N/V, headache', '2006-04-05');

INSERT INTO records(patient_id, title, description, date) VALUES(2, 'Continued Sore Throat','Ms. Bingham is a 24 yo woman complaining of continued sore throat since April 2006. She has never had a similar problem in the past. She has some difficulty swallowing with pain. No sense of choking or dysphagia. She continues to have fatigue and anorexia. She has not taken her temperature, and has no cough or rhinorrhea. She desnies seasonal allergies and post-nasal drip', '2006-06-12');