INSERT INTO patients(first_name, last_name) VALUES('John', 'Smith');

INSERT INTO patients(first_name, last_name) VALUES('Jane', 'Bingham');

INSERT INTO records(patient_id, title, description, date) VALUES(1, 'Initial Visit #1', 'Mr. Smith is a 66-year-old gentleman formally followed at Carolina Premier who presents to obtain a new primary care physician secondary to insurance changes. He has a past medical history significant for a myocardial infarction in 1994. His cholesterol has been fine. Catheterization showed a possible "kink" in one of his vessels and it was thought that he had a possible "eddy" of current which led to a clot. He has been on Coumadin since then as well as a calcium channel blocker with the thought that there may have been a superimposed spasm. He has had several unremarkable stress tests since then. He works out on a Nordic-Track three times a week without any chest pain or shortness of breath. He has a history of possible peptic ulcer disease in 1981. He was treated with H2 blockers and his symptoms resolved. He has never had any bleeding to his knowledge. He had a hernia repair bilaterally in 1989 and surgery for a right knee cyst in 1999, all of which went well. He also has about a year long history of right buttock pain. This happens only when he is sitting for some time and does not change position. It does not happen when he is walking or exercising. He wonders if it might be pyriformis syndrome. If he changes positions frequently or stretches his legs, this seems to help. He has no acute complaints today and is here to get plugged into the system. He does wonder if there is anything else that can be done about his buttock pain.', '2006-04-05');

INSERT INTO records(patient_id, title, description, date) VALUES(1, 'Initial Visit #2', 'Mr. Smith is a 66-year-old gentleman new to our Clinic. He had been followed by Dr. Jones at Kernodle Clinic. Mr. Smith has a past medical history that includes hypertension for more than five years. It sounds like he has fairly severe white coat hypertension. Apparently, he has home readings consistently 30 points below what he gets in the office. He had been on Capoten in the past and gotten a cough with that. He had been on Norvasc in the past, but then stopped it for unclear reasons. More recently, he has been on Hyzaar. He also has hypercholesterolemia and has been on Lipitor. He has for the past year or so felt that his hands and feet were "burning up" at night. He reports that "he can almost see the heat waves from them." He thinks this is a medication side effect. On his own, he stopped his Lipitor three weeks ago. He has not noticed any difference in his symptoms. He otherwise feels well and has no complaints.', '2006-5-01');


INSERT INTO records(patient_id, title, description, date) VALUES(1, 'Chronic Issues', 'Mr. Smith is a 66-year-old gentleman with coronary artery disease, hypertension, hypercholesterolemia, COPD and tobacco abuse. He reports doing well. He did have some more knee pain for a few weeks, but this has resolved. He is having more trouble with his sinuses. I had started him on Flonase back in December. He says this has not really helped. Over the past couple weeks he has had significant congestion and thick discharge. No fevers or headaches but does have diffuse upper right-sided teeth pain. He denies any chest pains, palpitations, PND, orthopnea, edema or syncope. His breathing is doing fine. No cough. He continues to smoke about half-a-pack per day. He plans on trying the patches again.', '2000-10-12');

INSERT INTO records(patient_id, title, description) VALUES(1, 'More Chronic Issues', 'Mr. Smith is a 66-year-old gentleman with hypertension and hypercholesterolemia. He reports he is overall doing well. He is not having any trouble with his medications. His blood pressures generally have been running around 140/90 at home. He has been having low back pain for the past 6 months. It is more on the right side and occurs intermittently throughout the day. No known initial precipitating event. He denies any radiation down his legs, any fevers, night sweats, weight loss, or bowel or bladder problems. Of note, he did have significant radiation in this area many years ago for treatment for skin cancer. He is not getting much exercise.');

INSERT INTO records(patient_id, title, description, date) VALUES(1, 'Post Hospitalization', 'Mr. Smith is a 46-year-old gentleman with hypertension, hypercholesterolemia, severe hand and feet dermatitis and tobacco abuse. He presents for follow-up of hospitalization at Rex. He presented 5 days ago with 24 hours of mid epigastric pain. This did go away with nitroglycerin in an urgent care clinic. EKG showed minimal Q-waves inferiorly. He ruled out. He had an exercise treadmill test, which showed 1 mm ST depression in the lateral leads without chest pain, but the test was limited by severe leg pain/claudication. He also had a chest x-ray, which showed a small nodular density posterior to the heart on the lateral view. It was felt to be probably a vessel seen on end. He was discharged on his usual medications to follow up here. Today, he reports he continues to feel well and that his midepigastric pain has not returned. Since I saw him last, he has started using his treadmill at home. He has not gotten any chest pain or midepigastric pain or shortness of breath with this, but has felt a burning in his calves. On the plus side, his dermatitis is doing the best that it has in more than 15 years. He is not sure why this is happening. He is also tapering down his smoking. He is down to a pack and a half a day. He is hoping to eventually quit.', '2010-06-25');

INSERT INTO records(patient_id, title, description, date) VALUES(2, 'Sore Throat', 'Ms. Bingham is a 24 yo woman who complains of worsening sore throat since yesterday morning. She has never had a similar problem in the past. She has no difficulty swallowing, but notes that swallowing makes the pain worse. Nothing makes it better. There is no SOB or sensation of choking or dysphagia. She has fatigue and has had some anorexia since the symptoms began. She has had some subjective fevers at home but has not taken her temperature. She has had no cough or rhinorrhea. There are no sick contacts at home or at work. She denies seasonal allergies and post-nasal drip. ROS: No chest pain, cough, wheezing, abdominal pain, N/V, headache', '2006-04-05');

INSERT INTO records(patient_id, title, description, date) VALUES(2, 'Continued Sore Throat','Ms. Bingham is a 24 yo woman complaining of continued sore throat since April 2006. She has never had a similar problem in the past. She has some difficulty swallowing with pain. No sense of choking or dysphagia. She continues to have fatigue and anorexia. She has not taken her temperature, and has no cough or rhinorrhea. She desnies seasonal allergies and post-nasal drip', '2006-06-12');